/* Auto-generated by build.js on Cloud Run startup — do not edit manually */
/* ローカル開発時のみここに直接記載（このファイルはgitignore対象） */
window.ENV = {
  FIREBASE_API_KEY:    '',
  FIREBASE_PROJECT_ID: '',
  FIREBASE_APP_ID:     '',
  BREVO_API_KEY:       '',
  BREVO_FROM_EMAIL:    'noreply@nfz33.com',
};
