#!/usr/bin/env node
/* build.js — Cloud Run起動時に環境変数から js/_env.js を生成 */
const fs = require('fs');

const {
  FIREBASE_API_KEY    = '',
  FIREBASE_PROJECT_ID = '',
  FIREBASE_APP_ID     = '',
  BREVO_API_KEY       = '',
  BREVO_FROM_EMAIL    = 'noreply@nfz33.com',
  APP_PASSWORD        = 'linkup2024',
} = process.env;

const content = `/* Auto-generated by build.js — do not edit manually */
window.ENV = {
  FIREBASE_API_KEY:    ${JSON.stringify(FIREBASE_API_KEY)},
  FIREBASE_PROJECT_ID: ${JSON.stringify(FIREBASE_PROJECT_ID)},
  FIREBASE_APP_ID:     ${JSON.stringify(FIREBASE_APP_ID)},
  BREVO_API_KEY:       ${JSON.stringify(BREVO_API_KEY)},
  BREVO_FROM_EMAIL:    ${JSON.stringify(BREVO_FROM_EMAIL)},
};
`;

fs.writeFileSync('/var/www/html/js/_env.js', content, 'utf-8');
console.log('✅ js/_env.js を生成しました');
console.log('   FIREBASE_PROJECT_ID:', FIREBASE_PROJECT_ID ? '設定済み ✅' : '未設定 ⚠️');
console.log('   BREVO_API_KEY:      ', BREVO_API_KEY       ? '設定済み ✅' : '未設定 ⚠️');
