#!/usr/bin/env node
const fs = require('fs');

const {
  SUPABASE_URL      = 'https://ehovgxyqlongollwyrml.supabase.co',
  SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVob3ZneHlxbG9uZ29sbHd5cm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NzcyMDgsImV4cCI6MjA4ODI1MzIwOH0.rdkzvNrsO8PkKDuMJNZwqY0pQDnabfVcmJnDhiv1wfc',
  RESEND_API_KEY    = 're_2uUwkqYF_QELAZsUopJCY2KC3h2Ngw75J',
  RESEND_FROM_EMAIL = 'estimate@nfz33.com',
} = process.env;

const content = `/* Auto-generated by build.js */
window.ENV = {
  SUPABASE_URL:      ${JSON.stringify(SUPABASE_URL)},
  SUPABASE_ANON_KEY: ${JSON.stringify(SUPABASE_ANON_KEY)},
  RESEND_API_KEY:    ${JSON.stringify(RESEND_API_KEY)},
  RESEND_FROM_EMAIL: ${JSON.stringify(RESEND_FROM_EMAIL)},
};
`;

fs.writeFileSync('js/_env.js', content, 'utf-8');
console.log('✅ js/_env.js を生成しました');
console.log('   SUPABASE:', SUPABASE_URL ? '設定済み ✅' : '未設定 ⚠️');
console.log('   RESEND:  ', RESEND_API_KEY ? '設定済み ✅' : '未設定 ⚠️');
